### PR TITLE
Base methods

### PR DESCRIPTION
**Pull request by boazmohar**
@freeman-lab @sethvincent  Thanks for getting me set up on this.
This would solve #2 
The only problem I see is that the conversion to markdown of the:

``` python
"""
see also
--------
"""
```

Is not really working, check out the base and data class methods.
We can either fix it in `myops` or remove from `thunder`, what do you think?

### CODE REVIEW

**Comment by freeman-lab** [comment]
Nice @boazmohar ! Looking at what's here, I'd say just drop those particular "see also" bits from `thunder` cause they don't actually add much, and then we'll be all done with this. But maybe open an issue on `myopts` so we remember to fix it at some point.

**Comment by boazmohar** [comment]
@freeman-lab Done

**Comment by freeman-lab** [comment]
Looking good @boazmohar ! One last small change... in the contents list, I'd move `blocks` so it comes after the `series` and `images` items.

**Comment by boazmohar** [comment]
@freeman-lab  Thanks! merged master and moved `blocks`.

**Comment by freeman-lab** [comment]
perfect! LGTM, merging in, thanks @boazmohar !

**Comment by freeman-lab** [comment]
Published updated version at http://docs.thunder-project.org/, thanks again @boazmohar !

**Pull request merged**
